-- Expand Room Table
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "capacity" INTEGER DEFAULT 2;
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "gallery" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "amenities_list" TEXT[] DEFAULT '{}'::text[];

-- Expand Guest Table
ALTER TABLE "Guest" ADD COLUMN IF NOT EXISTS "nationality" TEXT;
ALTER TABLE "Guest" ADD COLUMN IF NOT EXISTS "id_number" TEXT;
ALTER TABLE "Guest" ADD COLUMN IF NOT EXISTS "dob" DATE;
ALTER TABLE "Guest" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Guest" ADD COLUMN IF NOT EXISTS "notes" TEXT;
